# This is a config for E2B sandbox template.
# You can use template ID (q3flt8me7cnqx4v8m24s) or template name (vibe-nextjs-mayur78) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-mayur78") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-mayur78") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-mayur78')

team_id = "aa791524-d2fa-4f80-a8e0-5095dd46ffb7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-mayur78"
template_id = "q3flt8me7cnqx4v8m24s"
